In [1]:
a = 10

In [2]:
b = 20
c = a + b

In [3]:
c

30

In [5]:
print(a)

10


In [6]:
# numpy   : numarical python


In [7]:
a = [1, 2, 3, 4, 5]

In [8]:
type(a)

list

In [9]:
lst = [1, 2, 3, "hlo", 100.9]

In [10]:
type(lst)

list

In [11]:
# numpy : python, c
# 50x

In [12]:
# objects

In [13]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [14]:
import numpy as np

In [15]:
arr = np.array(12)

In [16]:
type(arr)

numpy.ndarray

In [18]:
arr = np.array([2, 3, 4, 5, 1])

In [19]:
arr

array([2, 3, 4, 5, 1])

In [20]:
arr.ndim

1

In [22]:
arr1 = np.array([[2, 3, 4, 5, 2, 8], [3, 4, 5, 6, 7, 0]])

In [24]:
arr1

array([[2, 3, 4, 5, 2, 8],
       [3, 4, 5, 6, 7, 0]])

In [25]:
arr1.ndim

2

In [26]:
arr2 = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[23, 45, 23, 23], [3, 4, 5, 6]]])

In [27]:
arr2


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[23, 45, 23, 23],
        [ 3,  4,  5,  6]]])

In [28]:
arr2.ndim

3

In [43]:
ar = np.array([2, 3, 4, 5, 2, 12])

In [44]:
# ar
# ar.ndim

In [45]:
ar[4] + ar[1]

5

In [47]:
ar[1 : 5]

array([3, 4, 5, 2])

In [48]:
# [strat : end : incremnet]

# strat = 0
# end = n- 1
# increment = 1

In [49]:
ar[: : -1]

array([12,  2,  5,  4,  3,  2])

In [52]:
x = np.array([[2, 3, 4, 5, 1], [3, 4, 5, 2, 4]])

In [55]:
x[1][3]

2

In [57]:
x[0][3]

5

In [58]:
y = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [59]:
y.ndim

3

In [63]:
y[1][1][0]

10

In [65]:
y[1][1][1 : ]

array([11, 12])