In [2]:
# numpy : 

# ndarray : array()



In [4]:
!pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/98/d7/1cc7a11118408ad21a5379ff2a4e0b0e27504c68ef6e808ebaa90ee95902/numpy-1.26.0-cp312-cp312-win_amd64.whl.metadata
     ---------------------------------------- 0.0/61.1 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.1 kB ? eta -:--:--
     ------------ ------------------------- 20.5/61.1 kB 217.9 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/61.1 kB 220.2 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.1 kB 292.6 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.1 kB 292.6 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.1 kB 292.6 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.1 kB 292.6 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.1 kB 292.6 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.1 kB 292.6 kB/s eta 0:00:01
     -----

In [5]:
import numpy as np

In [6]:
ar = np.array([1, 2, 3, 4])

In [8]:
ar

array([1, 2, 3, 4])

In [10]:
type(ar)

int

In [11]:
ar.ndim

1

In [14]:
zx = np.array([[[2, 3, 4], [3, 4, 5]], [[4, 2, 3], [0, 6, 7]]])

In [15]:
zx.ndim

3

In [16]:
zx

array([[[2, 3, 4],
        [3, 4, 5]],

       [[4, 2, 3],
        [0, 6, 7]]])

In [17]:
# shape

a = np.array([[3, 4, 5], [6, 7, 8]])

In [18]:
a.shape

(2, 3)

In [19]:
a

array([[3, 4, 5],
       [6, 7, 8]])

In [20]:
zx = np.array([[[2, 3, 4], [3, 4, 5]], [[4, 2, 3], [0, 6, 7]]])

In [21]:
zx.shape

(2, 2, 3)

In [22]:
zx

array([[[2, 3, 4],
        [3, 4, 5]],

       [[4, 2, 3],
        [0, 6, 7]]])

In [39]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [40]:
arr.ndim

1

In [41]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
# reshape
zx = arr.reshape(5, 2)

In [43]:
zx

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [46]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 2])

In [50]:
zx = a + b

In [51]:
zx

array([ 7,  9, 11, 13,  7])

In [56]:
c = np.concatenate((a, b), axis = 0)

In [57]:
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 2])

In [60]:
arr = np.array([1, 2, 3, 8, 4, 5, 6, 7, 8, 9, 10, 8])

In [62]:
np.where(arr == 8)

(array([ 3,  8, 11], dtype=int64),)

In [63]:
a = np.array([3, 5, 1, 3, 7, 5, 6, 7, 3, 5, 6, 3, 11])

In [64]:
a

array([ 3,  5,  1,  3,  7,  5,  6,  7,  3,  5,  6,  3, 11])

In [65]:
zx = np.sort(a)

In [66]:
zx

array([ 1,  3,  3,  3,  3,  5,  5,  5,  6,  6,  7,  7, 11])